### ISSUE TITLE
Doorbell notifications stopped working

### ISSUE THREAD

**Issue by niels-vd** [birkir/homebridge-plugin-eufy-security#7]
Battery doorbell was working fine until about yesterday. After intstalling v0.1.2 this morning I hoped Home notifications would start working again, but no luck. The camera's still exposed to Homekit, but no more notifications (before I used to get double notifications). It seems like nothing's happening in the Homebridge logs either when the bell's rung. Anybody else experiencing this issue?

**Comment by Stichoza** [comment]
Related to #5. I'm preparing a pull request to fix that asap

**Comment by niels-vd** [comment]
> Related to #5. I'm preparing a pull request to fix that asap

Thanks for the response @Stichoza. Would be great if you're able to fix it!

**Comment by Stichoza** [comment]
I guess I was wrong, it's not related to that issue. It doesn't go to this line: https://github.com/birkir/homebridge-plugin-eufy-security/blob/dadccc5ad316fec40c919eaecc8a337b2872e2c0/src/platform.ts#L116

Instead I'm getting this error:

```
Loading accessory from cache: Doorbell
push client disabled
```

I removed the doorbell config, restarted, added the doorbell config and restarted again, but got same `push client disabled` error even when device was not restored from cache.

I thin this is more related to this commit: https://github.com/birkir/homebridge-plugin-eufy-security/commit/c37e2d91d30f203a0602b8dd8ddb6fdb90b6c2bb

**Comment by niels-vd** [comment]
I think you're right about that commit. I just noticed one of my devices kept receiving notifications up until I upgraded to v0.1.2.

**Comment by Stichoza** [comment]
I managed to enable push client by adding `"pushClient": true` to homebridge config. No idea why it works like that, because default value for `enablePush` config value is `true` anyways.

I see `push client enabled` message in logs after I added that config, but now I'm getting the following error which causes homebridge to restart endlessly:


```
[07/12/2020, 19:37:29] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:84:11)
    at Object.generate (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:9:11)
    at PushClient.callback (/usr/lib/node_modules/homebridge-plugin-eufy-security/src/platform.ts:111:46)
    at PushClient.handleParsedMessage (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client.service.js:206:26)
    at PushClientParser.<anonymous> (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client.service.js:103:63)
    at PushClientParser.emit (events.js:315:20)
    at PushClientParser.onGotMessageBytes (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:150:14)
    at PushClientParser.handleFullMessage (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:79:22)
    at PushClientParser.waitForData (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:64:18)
    at PushClientParser.onGotMessageSize (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:124:18)
[07/12/2020, 19:37:29] Got SIGTERM, shutting down Homebridge...
```

**Comment by niels-vd** [comment]
I tried the same and get no error messages anymore, but no 'client enabled' message either. So not working unfortunately.

**Comment by Stichoza** [comment]
Are you running homebridge with `-D` (debug log) flag?

**Comment by niels-vd** [comment]
> Are you running homebridge with `-D` (debug log) flag?

Not at the moment, but I'll try adding the debug log when I get back to work!

**Comment by niels-vd** [comment]
Ok, I did a quick check and had to restart the docker container to add the debug environment parameter. After the restart: no more error message ... Restarting Homebridge did nothing, but killing the container did ...

Kind of annoying I didn't get any useful logs though ...

**Comment by niels-vd** [comment]
After reinstalling the plugin I get the same error message again. Nothing strange in the debug log either. I saved it, so let me know what could be useful information (the whole debug log is quite large of course)

**Comment by Insomniac86** [comment]
Hi guys,
I just installed the plugin, and I get endless lines of [EufySecurityHomebridgePlugin] failed to confirm push token"
Is this not an issue at the Eufy side?

Cheers

**Comment by niels-vd** [comment]
> Hi guys,
> I just installed the plugin, and I get endless lines of [EufySecurityHomebridgePlugin] failed to confirm push token"
> Is this not an issue at the Eufy side?
> 
> Cheers

I don't think so, since this error pops up since v0.1.2. The versions before didn't have this issue. Besides that, the Eufy app itself's still pushing notifications.

**Comment by Insomniac86** [comment]
> > Hi guys,
> > I just installed the plugin, and I get endless lines of [EufySecurityHomebridgePlugin] failed to confirm push token"
> > Is this not an issue at the Eufy side?
> > Cheers
> 
> I don't think so, since this error pops up since v0.1.2. The versions before didn't have this issue. Besides that, the Eufy app itself's still pushing notifications.

Gotcha.... Just bad timing on me installing it then!

**Comment by birkir** [comment]
Fixed with 0.1.3

**Comment by jdraxgit** [comment]
Still have this error of endless lines of failed to confirm push token in 0.1.3. But then again I can't get this plugin to work on any version yet

**Comment by birkir** [comment]
> Still have this error of endless lines of failed to confirm push token in 0.1.3. But then again I can't get this plugin to work on any version yet

Sounds like invalid credentials. What happens if you disable push?

**Comment by jdraxgit** [comment]
I get an error for an unhandledpromiserejectionwarning: HTTPerror: Response Code 401 (unauthorized)

The same login credentials work with the Eufy Security app for a guest account (not typing them in, using password mananager app). 2FA is not enabled

**Comment by Insomniac86** [comment]
Installed 0.1.3
Now I'm getting **EufySecurityHomebridgePlugin registering a push token timed out** If I disable the push token, I don't get the error, however I can't see how I add the camera into my HomeKit. I go to add devices> I don't have a code, But don't see it show up in the list to add additional home bridge drives like you need to for TV's and Camera's.

I'll have back in a few weeks and see how it's going.

Best of luck with it!

**Comment by niels-vd** [comment]
> Fixed with 0.1.3

I installed this version, but still getting the same error:
[12/9/2020, 7:32:13 AM] [EufySecurityHomebridgePlugin] registering a push token timed out

The camera's still working, so for me nothing changed

**Comment by cusas123** [comment]
I'm getting the same (push token timed out) error. I'm using Hoobs though. My camera doesn't show up at all in Homekit.

**Comment by PeteBurgess** [comment]
I think the issue is more likely to do with the dependency of eufy-node-client 0.3.1. That’s the NPM published version and it has a bug where it’ll just constantly re-auth instead of hooking up a push client. The version on that’s on GitHub fixes that.

**Comment by karesake** [comment]
Unfortunately still nothing works. The best version was 0.1.1. There at least the ringing on the HomePod and watching the stream worked (even if it takes a very long time). With all versions after that, even with the latest 0.1.3, the ringing on the HomePod does not work.

**Comment by TheBassfly** [comment]
I'm also with the problem, that the Plugin doesn't work anymore. Even with the new 0.1.4. Version.

(node:30726) UnhandledPromiseRejectionWarning: Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 26006 - Email address or password incorrect.
    at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30726) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30726) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

This is the error in the log.

**Comment by TheBassfly** [comment]
I'm also struggling with the plugin. Even the new 0.1.4 Version doesn't work.

Here is the Error from the Log:

(node:31065) UnhandledPromiseRejectionWarning: Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100027 - Failed to request.
    at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31065) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31065) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jdraxgit** [comment]
I have the same error as post above

**Comment by karesake** [comment]
The camera also doesnt work with the old 0.1.1 Version anymore. 

https://mysecurity.eufylife.com/api/v1/passport/login
This adress is not available

**Comment by adekka** [comment]
I got the stream working but no notifcations. Let me know if I can share something like setup, versions or whatever to help debug.

**Comment by jdraxgit** [comment]
> I got the stream working but no notifcations. Let me know if I can share something like setup, versions or whatever to help debug.

Which doorbell model are you using?

**Comment by adekka** [comment]
The T8210 - battery powered version

**Comment by jdraxgit** [comment]
> The T8210 - battery powered version

So what version of homebridge and the plug-in are you running? Is your account you logged into guest or admin? Any thing special you did that is not discussed in the setup of this plugin?

**Comment by Stichoza** [comment]
> I managed to enable push client by adding `"pushClient": true` to homebridge config. No idea why it works like that, because default value for `enablePush` config value is `true` anyways.
> 
> I see `push client enabled` message in logs after I added that config, but now I'm getting the following error which causes homebridge to restart endlessly:
> 
> ```
> [07/12/2020, 19:37:29] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
>     at Hash.update (internal/crypto/hash.js:84:11)
>     at Object.generate (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:9:11)
>     at PushClient.callback (/usr/lib/node_modules/homebridge-plugin-eufy-security/src/platform.ts:111:46)
>     at PushClient.handleParsedMessage (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client.service.js:206:26)
>     at PushClientParser.<anonymous> (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client.service.js:103:63)
>     at PushClientParser.emit (events.js:315:20)
>     at PushClientParser.onGotMessageBytes (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:150:14)
>     at PushClientParser.handleFullMessage (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:79:22)
>     at PushClientParser.waitForData (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:64:18)
>     at PushClientParser.onGotMessageSize (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:124:18)
> [07/12/2020, 19:37:29] Got SIGTERM, shutting down Homebridge...
> ```

I'm still stuck at the restart loop caused by this error. It **only** happens when I set `pushClient` config value to `true`. Did anybody found a workaround for this?

**Comment by adekka** [comment]
> > The T8210 - battery powered version
> 
> So what version of homebridge and the plug-in are you running? Is your account you logged into guest or admin? Any thing special you did that is not discussed in the setup of this plugin?

I created a new guest account which has only access to the doorbell. Besides that I installed the plugin on an already installed homebridge on a RPI via the Homebridge UI plugin. I added 'name:' to the configuration as that was missing when I installed v0.1.1. No other configurations done. Nothing weird found in the log.

Plugin: v0.1.4
Homebridge: v1.1.6
Node: v14.15.0
NPM: v6.14.8

**Comment by jdraxgit** [comment]
@adekka is your homebase 2 connected to homekit? Your setup sounds really close to mine except my node version is 14.15.1

**Comment by adekka** [comment]
Yes it is. I have 2 eufycams. Both are homekit enabled with HSV.

**Comment by jdraxgit** [comment]
Interesting that yours works with stream and my almost exact same setup won't show anything. What version of homebase and doorbell firmware is running on your end?

**Comment by karesake** [comment]
Found it! Eufy has blocked my old account. I Created a new account, saved it into config and now the doorbell is back in home app and the stream is working

**Comment by karesake** [comment]
New Account was also Blocked in 10 Minutes.

**Comment by adekka** [comment]
Or wait for the Circle doorbell ;)

However, it is strange that your account is blocked and mine istn't

**Comment by Stichoza** [comment]
Logitech Circle is out already! Guess I'll throw away my Eufy too 😂

**Comment by ktsi** [comment]
Hi all,

Is it safe to install the plug-in or is there a possibility Eufy locks my account? 

Thanks

**Comment by neumanns** [comment]
Yes I can confirm that. My Eufy account has been blocked. If I log out of the "Eufy Security" app, I can no longer log in.

Apparently there is an abuse of the API. Too many requests (push tokens) in a short time.

The Eufy API thinks it is spam.

**Comment by ktsi** [comment]
Yeah but does this happen to everyone? Is there anyone with a working plugin?

I have personally tested a very old version (0.04 I think) and I had no side effects.

**Comment by niels-vd** [comment]
Didn't happen to me yet, and it's still not working

**Comment by ktsi** [comment]
So we are waiting for the dev to solve some problems before we have a working and safe plugin.

In any case thanks a lot @birkir for your efforts so far.

**Comment by niels-vd** [comment]
Yes, I guess it's all in the hands of the big man now

**Comment by Stichoza** [comment]
I'm not blocked but getting login failed errors in logs sometimes (Not an account block, because I'm able to log in a few hours later). Guess there's some login throttling on their end. Don't know why it fails tho, do they throttle successful logins too? 😬

```UnhandledPromiseRejectionWarning: Error: Request failed: https://security-app-eu.eufylife.com/v1/passport/login -> 100028 - Failed to request.```

**BUT** the same happens on the eufy website:

<img width="730" alt="image" src="https://user-images.githubusercontent.com/1139050/101991773-4b563a00-3cc8-11eb-8bcb-a51cf81ffa13.png">

It has the same code and error message in network console. Come on eufy..

**Comment by birkir** [comment]
There may be a fix in the works that will solve this.

https://github.com/JanLoebel/eufy-node-client/commit/99bc884771ad1bcb8d9354590060be5514a6cb8d

When it will be released I’ll update the dependency!

For what it’s worth, my doorbell is working well 😀 video and notifications

**Comment by ktsi** [comment]
Patiently waiting.

**Comment by karesake** [comment]
Is something else going on here?
